###
POST http://localhost:3006/user/create
Content-Type: application/json

{
    "name": "Tom",
    "email": "tomtom@email.com",
    "password": "33899"
}

###
GET http://localhost:3006/user/get
Content-Type: application/json

###
POST http://localhost:3006/movie/create
Content-Type: application/json

{
    "title" : "A Volta dos Que Não Foram",
    "description" : "Não foram pra dizer como voltaram",
    "duration_in_minutes" : 125,
    "year_of_release" : 2015
}